---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8082'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.20.2
    ports:
    - 8082:8082
    restart: on-failure:0
    volumes:
      - ./dbdata:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      QUERY_MAXIMUM_RESULTS: 10000
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      ENABLE_MODULES: 'text2vec-openai,text2vec-cohere,text2vec-huggingface,generative-openai'
      CLUSTER_HOSTNAME: 'node1'
...